apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://opensearch-project.github.io/helm-charts
      chart: opensearch
      targetRevision: 2.x.x
      helm:
        valueFiles:
          - $values/kubernetes/logging/opensearch-values.yaml
    - repoURL: https://github.com/ZaheerrAhmed/cloud-native-dr-platform
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/kubernetes/logging/fluent-bit-values.yaml
    - repoURL: https://github.com/ZaheerrAhmed/cloud-native-dr-platform
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
